# Project: PhylogeneticTreeFramework
# Makefile created by Dev-C++ 5.6.2 and nodified by User

ARCH := $(shell getconf LONG_BIT)

CPP_FLAGS_32 := -D32_BIT ...  Some 32 specific compiler flags ...
CPP_FLAGS_64 := -D64_BIT

CPP_FLAGS := $(CPP_FLAGS_$(ARCH))

CPP      = g++ -D__DEBUG__
CC       = gcc -D__DEBUG__

OBJ      = main.o compositionVectors.o wordContext.o neighborJoining.o GraphClass.o spacedWordFrequency.o baseSub.o
LINKOBJ  = main.o compositionVectors.o wordContext.o neighborJoining.o GraphClass.o spacedWordFrequency.o baseSub.o

BIN      = PhyloTree.exe

RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

compositionVectors.o: compositionVectors.cpp
	$(CPP) -c compositionVectors.cpp -o compositionVectors.o $(CXXFLAGS)

wordContext.o: wordContext.cpp
	$(CPP) -c wordContext.cpp -o wordContext.o $(CXXFLAGS)

neighborJoining.o: neighborJoining.cpp
	$(CPP) -c neighborJoining.cpp -o neighborJoining.o $(CXXFLAGS)

GraphClass.o: GraphClass.cpp
	$(CPP) -c GraphClass.cpp -o GraphClass.o $(CXXFLAGS)

spacedWordFrequency.o: spacedWordFrequency.cpp
	$(CPP) -c spacedWordFrequency.cpp -o spacedWordFrequency.o $(CXXFLAGS)

baseSub.o: baseSub.cpp
	$(CPP) -c baseSub.cpp -o baseSub.o $(CXXFLAGS)
